CREATE TABLE Contacts(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(255) NOT NULL,
	COMPANY VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	PHONE_NUMBER VARCHAR(10) UNIQUE,
);	
INSERT INTO Contacts(NAME,COMPANY, EMAIL,PHONE_NUMBER) 
values('viet','feu','vietdinh@gmail.com','0987654233')

select * from Contacts